#!/usr/bin/env python3
"""HelioFrame process-based Python worker.

This worker accepts a single positional argument pointing to an input
manifest JSON file. It reads a decoded frame directory and writes the exact
same frames to an output frame directory (pass-through behavior for HF-014).

The worker writes an output manifest next to the provided input manifest unless
`output_manifest_path` is set in the input payload.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any

INPUT_SCHEMA_VERSION = "1.0.0"
OUTPUT_SCHEMA_VERSION = "1.0.0"


@dataclass(frozen=True)
class FrameEntry:
    index: int
    file_name: str


@dataclass(frozen=True)
class InputManifest:
    schema_version: str
    run_id: str
    clip_id: str
    input_frames_dir: Path
    output_frames_dir: Path
    output_manifest_path: Path
    frames: list[FrameEntry]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="HelioFrame Python worker (process-based manifest I/O)."
    )
    parser.add_argument(
        "manifest_path",
        type=Path,
        help="Path to the input clip manifest JSON generated by Rust.",
    )
    return parser.parse_args()


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _require_string(payload: dict[str, Any], key: str) -> str:
    value = payload.get(key)
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"manifest field `{key}` must be a non-empty string")
    return value


def load_input_manifest(path: Path) -> InputManifest:
    payload = json.loads(path.read_text())
    if not isinstance(payload, dict):
        raise ValueError("input manifest must be a JSON object")

    schema_version = _require_string(payload, "schema_version")
    if schema_version != INPUT_SCHEMA_VERSION:
        raise ValueError(
            f"unsupported input schema_version `{schema_version}`; expected `{INPUT_SCHEMA_VERSION}`"
        )

    raw_frames = payload.get("frames")
    if not isinstance(raw_frames, list) or not raw_frames:
        raise ValueError("manifest field `frames` must be a non-empty array")

    parsed_frames: list[FrameEntry] = []
    for raw_frame in raw_frames:
        if not isinstance(raw_frame, dict):
            raise ValueError("each frame entry must be an object")
        index = raw_frame.get("index")
        file_name = raw_frame.get("file_name")
        if not isinstance(index, int) or index < 0:
            raise ValueError("frame `index` must be a non-negative integer")
        if not isinstance(file_name, str) or not file_name.strip():
            raise ValueError("frame `file_name` must be a non-empty string")
        parsed_frames.append(FrameEntry(index=index, file_name=file_name))

    output_manifest = payload.get("output_manifest_path")
    default_output_manifest = path.parent / "worker-output-manifest.json"

    return InputManifest(
        schema_version=schema_version,
        run_id=_require_string(payload, "run_id"),
        clip_id=_require_string(payload, "clip_id"),
        input_frames_dir=Path(_require_string(payload, "input_frames_dir")),
        output_frames_dir=Path(_require_string(payload, "output_frames_dir")),
        output_manifest_path=Path(output_manifest)
        if isinstance(output_manifest, str) and output_manifest.strip()
        else default_output_manifest,
        frames=parsed_frames,
    )


def run_worker(manifest: InputManifest) -> dict[str, Any]:
    manifest.input_frames_dir.mkdir(parents=True, exist_ok=True)
    manifest.output_frames_dir.mkdir(parents=True, exist_ok=True)

    output_frames: list[dict[str, Any]] = []

    for frame in manifest.frames:
        source = manifest.input_frames_dir / frame.file_name
        if not source.exists():
            raise FileNotFoundError(f"missing expected frame: {source}")

        destination = manifest.output_frames_dir / frame.file_name
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)

        output_frames.append(
            {
                "index": frame.index,
                "file_name": frame.file_name,
                "source_sha256": _sha256(source),
                "output_sha256": _sha256(destination),
            }
        )

    return {
        "schema_version": OUTPUT_SCHEMA_VERSION,
        "run_id": manifest.run_id,
        "clip_id": manifest.clip_id,
        "status": "ok",
        "mode": "passthrough",
        "input_manifest_schema_version": manifest.schema_version,
        "output_frames_dir": str(manifest.output_frames_dir),
        "frame_count": len(output_frames),
        "frames": output_frames,
    }


def main() -> int:
    args = parse_args()
    manifest = load_input_manifest(args.manifest_path)
    result = run_worker(manifest)

    manifest.output_manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest.output_manifest_path.write_text(json.dumps(result, indent=2))
    print(json.dumps(result))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
