#!/usr/bin/env python3
"""HelioFrame process-based Python worker.

This worker accepts a single positional argument pointing to an input
manifest JSON file. It reads decoded input frames, runs a selected backend,
and writes processed frames plus an output manifest.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any

INPUT_SCHEMA_VERSION = "1.0.0"
OUTPUT_SCHEMA_VERSION = "1.0.0"


@dataclass(frozen=True)
class FrameEntry:
    index: int
    file_name: str


@dataclass(frozen=True)
class InputManifest:
    schema_version: str
    run_id: str
    clip_id: str
    backend: str
    backend_options: dict[str, Any]
    input_frames_dir: Path
    output_frames_dir: Path
    output_manifest_path: Path
    frames: list[FrameEntry]
    windows: list[dict[str, Any]] | None = None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="HelioFrame Python worker (process-based manifest I/O)."
    )
    parser.add_argument(
        "manifest_path",
        type=Path,
        help="Path to the input clip manifest JSON generated by Rust.",
    )
    return parser.parse_args()


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _require_string(payload: dict[str, Any], key: str) -> str:
    value = payload.get(key)
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"manifest field `{key}` must be a non-empty string")
    return value


def load_input_manifest(path: Path) -> InputManifest:
    payload = json.loads(path.read_text())
    if not isinstance(payload, dict):
        raise ValueError("input manifest must be a JSON object")

    schema_version = _require_string(payload, "schema_version")
    if schema_version != INPUT_SCHEMA_VERSION:
        raise ValueError(
            f"unsupported input schema_version `{schema_version}`; expected `{INPUT_SCHEMA_VERSION}`"
        )

    raw_frames = payload.get("frames")
    if not isinstance(raw_frames, list) or not raw_frames:
        raise ValueError("manifest field `frames` must be a non-empty array")

    parsed_frames: list[FrameEntry] = []
    for raw_frame in raw_frames:
        if not isinstance(raw_frame, dict):
            raise ValueError("each frame entry must be an object")
        index = raw_frame.get("index")
        file_name = raw_frame.get("file_name")
        if not isinstance(index, int) or index < 0:
            raise ValueError("frame `index` must be a non-negative integer")
        if not isinstance(file_name, str) or not file_name.strip():
            raise ValueError("frame `file_name` must be a non-empty string")
        parsed_frames.append(FrameEntry(index=index, file_name=file_name))

    output_manifest = payload.get("output_manifest_path")
    default_output_manifest = path.parent / "worker-output-manifest.json"

    backend = payload.get("backend")
    if backend is None:
        backend = payload.get("backend_name", "passthrough")
    if not isinstance(backend, str) or not backend.strip():
        raise ValueError("manifest field `backend` must be a non-empty string when provided")

    backend_options = payload.get("backend_options", {})
    if not isinstance(backend_options, dict):
        raise ValueError("manifest field `backend_options` must be an object")

    raw_windows = payload.get("windows")
    parsed_windows: list[dict[str, Any]] | None = None
    if isinstance(raw_windows, list) and raw_windows:
        parsed_windows = raw_windows

    return InputManifest(
        schema_version=schema_version,
        run_id=_require_string(payload, "run_id"),
        clip_id=_require_string(payload, "clip_id"),
        backend=backend,
        backend_options=backend_options,
        input_frames_dir=Path(_require_string(payload, "input_frames_dir")),
        output_frames_dir=Path(_require_string(payload, "output_frames_dir")),
        output_manifest_path=Path(output_manifest)
        if isinstance(output_manifest, str) and output_manifest.strip()
        else default_output_manifest,
        frames=parsed_frames,
        windows=parsed_windows,
    )


def _run_passthrough(manifest: InputManifest) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    output_frames: list[dict[str, Any]] = []

    for frame in manifest.frames:
        source = manifest.input_frames_dir / frame.file_name
        if not source.exists():
            raise FileNotFoundError(f"missing expected frame: {source}")

        destination = manifest.output_frames_dir / frame.file_name
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)

        output_frames.append(
            {
                "index": frame.index,
                "file_name": frame.file_name,
                "source_sha256": _sha256(source),
                "output_sha256": _sha256(destination),
            }
        )

    return output_frames, {"backend": "passthrough"}


def _run_realbasicvsr(manifest: InputManifest) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    options = manifest.backend_options
    model_path = Path(options.get("model_path", "models/realbasicvsr/realbasicvsr_x4.ts"))
    if not model_path.is_absolute():
        model_path = Path.cwd() / model_path

    from backends import RealBasicVSRBackend

    backend = RealBasicVSRBackend(
        model_path=model_path,
        device=str(options.get("device", "cuda")),
        window_size=int(options.get("window_size", 6)),
        overlap=int(options.get("overlap", 2)),
        precision=str(options.get("precision", "fp16")),
    )

    written, backend_meta = backend.run(manifest, sha256_fn=_sha256)
    output_frames = [
        {
            "index": frame.index,
            "file_name": frame.file_name,
            "source_sha256": frame.source_sha256,
            "output_sha256": frame.output_sha256,
        }
        for frame in written
    ]
    return output_frames, backend_meta



def _run_seedvr_teacher(manifest: InputManifest) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    options = manifest.backend_options
    model_path = Path(options.get("model_path", "models/seedvr-teacher/seedvr_teacher_v1.0.0.ts"))
    if not model_path.is_absolute():
        model_path = Path.cwd() / model_path

    from backends import SeedVRTeacherBackend

    backend = SeedVRTeacherBackend(
        model_path=model_path,
        model_version=str(options.get("model_version", "seedvr-teacher-v1.0.0")),
        expected_weights_sha256=str(
            options.get(
                "weights_sha256",
                "c2c0d9ec5b0c8c1f8b03419e7f3e462f8ab7604f53f6ed15ec5122f7e14b8079",
            )
        ),
        device=str(options.get("device", "cuda")),
        window_size=int(options.get("window_size", 12)),
        overlap=int(options.get("overlap", 4)),
        precision=str(options.get("precision", "fp32")),
        offline_only=bool(options.get("offline_only", True)),
    )

    written, backend_meta = backend.run(manifest, sha256_fn=_sha256)
    output_frames = [
        {
            "index": frame.index,
            "file_name": frame.file_name,
            "source_sha256": frame.source_sha256,
            "output_sha256": frame.output_sha256,
        }
        for frame in written
    ]
    return output_frames, backend_meta

def _run_detail_refiner(manifest: InputManifest) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    options = manifest.backend_options
    model_path = Path(options.get("model_path", "models/detail-refiner/detail_refiner_v1.0.0.ts"))
    if not model_path.is_absolute():
        model_path = Path.cwd() / model_path

    from backends import DetailRefinerBackend

    backend = DetailRefinerBackend(
        model_path=model_path,
        model_version=str(options.get("model_version", "detail-refiner-v1.0.0")),
        expected_weights_sha256=str(
            options.get(
                "weights_sha256",
                "b8d4f2a1e6c73950d2b1e4a8f7c3d6b9e5a2f8c1d7b4e0a3f6c9d2b5e8a1f4c7",
            )
        ),
        device=str(options.get("device", "cuda")),
        refinement_steps=int(options.get("refinement_steps", 6)),
        refinement_strength=float(options.get("refinement_strength", 0.4)),
        hf_energy_threshold=float(options.get("hf_energy_threshold", 0.25)),
        min_window_hf_ratio=float(options.get("min_window_hf_ratio", 0.10)),
        max_hf_flicker=float(options.get("max_hf_flicker", 0.12)),
        max_patch_shimmer=float(options.get("max_patch_shimmer", 0.08)),
        categories=options.get("categories"),
        patch_size=int(options.get("patch_size", 128)),
        precision=str(options.get("precision", "fp16")),
    )

    written, backend_meta = backend.run(manifest, sha256_fn=_sha256)
    output_frames = [
        {
            "index": frame.index,
            "file_name": frame.file_name,
            "source_sha256": frame.source_sha256,
            "output_sha256": frame.output_sha256,
        }
        for frame in written
    ]
    return output_frames, backend_meta


def _run_stcdit_studio(manifest: InputManifest) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    options = manifest.backend_options
    model_path = Path(options.get("model_path", "models/stcdit-studio/stcdit_studio_v1.0.0.ts"))
    if not model_path.is_absolute():
        model_path = Path.cwd() / model_path

    from backends import STCDiTStudioBackend

    backend = STCDiTStudioBackend(
        model_path=model_path,
        model_version=str(options.get("model_version", "stcdit-studio-v1.0.0")),
        expected_weights_sha256=str(
            options.get(
                "weights_sha256",
                "a7b3e1f0c4d29856e1a0f3b7c8d5e2a9f6b4c1d8e5a2f7b3c0d6e9a1f4b8c5d2",
            )
        ),
        device=str(options.get("device", "cuda")),
        window_size=int(options.get("window_size", 20)),
        overlap=int(options.get("overlap", 4)),
        precision=str(options.get("precision", "fp16")),
        diffusion_steps=int(options.get("diffusion_steps", 16)),
        guidance_scale=float(options.get("guidance_scale", 7.5)),
        anchor_frame_stride=int(options.get("anchor_frame_stride", 4)),
    )

    written, backend_meta = backend.run(manifest, sha256_fn=_sha256)
    output_frames = [
        {
            "index": frame.index,
            "file_name": frame.file_name,
            "source_sha256": frame.source_sha256,
            "output_sha256": frame.output_sha256,
        }
        for frame in written
    ]
    return output_frames, backend_meta


def run_worker(manifest: InputManifest) -> dict[str, Any]:
    manifest.input_frames_dir.mkdir(parents=True, exist_ok=True)
    manifest.output_frames_dir.mkdir(parents=True, exist_ok=True)

    backend_name = manifest.backend.strip().lower()
    if backend_name in {"passthrough", "classical-baseline"}:
        output_frames, backend_meta = _run_passthrough(manifest)
        mode = "passthrough"
    elif backend_name in {"realbasicvsr", "realbasicvsr-bridge"}:
        output_frames, backend_meta = _run_realbasicvsr(manifest)
        mode = "realbasicvsr"
    elif backend_name in {"seedvr-teacher", "seedvr_teacher"}:
        output_frames, backend_meta = _run_seedvr_teacher(manifest)
        mode = "seedvr-teacher"
    elif backend_name in {"stcdit-studio", "stcdit_studio"}:
        output_frames, backend_meta = _run_stcdit_studio(manifest)
        mode = "stcdit-studio"
    elif backend_name in {"detail-refiner", "detail_refiner"}:
        output_frames, backend_meta = _run_detail_refiner(manifest)
        mode = "detail-refiner"
    else:
        raise ValueError(f"unsupported worker backend `{manifest.backend}`")

    return {
        "schema_version": OUTPUT_SCHEMA_VERSION,
        "run_id": manifest.run_id,
        "clip_id": manifest.clip_id,
        "status": "ok",
        "mode": mode,
        "input_manifest_schema_version": manifest.schema_version,
        "output_frames_dir": str(manifest.output_frames_dir),
        "frame_count": len(output_frames),
        "frames": output_frames,
        "backend": backend_meta,
    }


def main() -> int:
    args = parse_args()
    manifest = load_input_manifest(args.manifest_path)
    result = run_worker(manifest)

    manifest.output_manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest.output_manifest_path.write_text(json.dumps(result, indent=2))
    print(json.dumps(result))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
